### ISSUE TITLE
Makefile rule failes silently

### ISSUE THREAD

**Issue by depp** [devkitPro/devkitarm-rules#2]
In `base_tools`, recipes with this definition will fail silently if `bin2s` is not installed (Make will incorrectly think it succeeded).

```make
define bin2o
	bin2s -a 4 -H `(echo $(<F) | tr . _)`.h $< | $(AS) -o $(<F).o
endef
```

This happens because the exit code of `bin2s` is ignored, which happens because it's on the left side of a pipe.

This can be fixed by setting `pipefail`. Here's one way to do it:

```make
	set -o pipefail; bin2s -a 4 ...
```

Note that this is a bash-ism, so it will not work on other shells. That may be a portability concern.

**Comment by WinterMute** [comment]
We came across a situation recently where we needed to pass the emitted source through gcc to get the right options for the assembler & it seemed more sensible to save the source & compile it from there instead. That ended up fixing this issue as a side effect.
