### ISSUE TITLE
C++20 modules only compile if their extension is .cpp

### ISSUE THREAD

**Issue by ChrisNonyminus** [devkitPro/devkitarm-rules#4]
I ran into this issue when experimenting with C++20 modules, when a module's extension was .cppm.
![image](https://user-images.githubusercontent.com/50080567/236457359-d75ece35-ac6d-4cf3-9d9b-93f89f30b7e0.png)

I was confused at first, until I realized that, due to the rules files, the makefile recipes don't take into account this wacky new feature and its possible file extensions (.ixx/.cppm/etc). Compiling the modules works if the module extensions are .cpp. [However, some IDEs expect or REQUIRE the modules to NOT have .cpp as an extension for some analysis features to work.](https://www.jetbrains.com/help/clion/support-for-c-20-modules.html)

![image](https://user-images.githubusercontent.com/50080567/236457969-5a512e17-d68b-41e9-8be8-5d60e340a924.png)

As you can tell, Clion accepts the module syntax just fine in this file but presumably it cannot "smartly" detect usage of the module in other files.

I'm sure this could be resolved by simply adding a recipe for .cppm and/or .ixx. I understand if this is not an important issue as C++20 modules are still uncharted territory compared to other new C++ features such as constexpr and concepts, but it would be cool to support this feature.

**Comment by fincs** [comment]
It looks like you're using CMake. Our CMake machinery does not use the Makefile rules in this repo (CMake generates its own rules). Can you post your project?

**Comment by ChrisNonyminus** [comment]
Sure: https://github.com/ChrisNonyminus/cpp20_modules_experiment

**Comment by fincs** [comment]
It looks like you're using a third party CMake module purportedly aiming to add support for building C++ modules. Moreover, said CMake module seems to have been written with Clang and MSVC in mind (not GCC), and does things which will likely fail under a cross compiler scenario (such as directly invoking the compiler in a custom command without taking into account platform flags). [Official support for C++ modules in CMake is still a work in progress](https://gitlab.kitware.com/cmake/cmake/-/issues/18355), so I'd advise you to exercise patience until it becomes available as part of a CMake release.
