### ISSUE TITLE
Compiling source files with the same name in subfolders

### ISSUE THREAD

**Issue by talanc** [devkitPro/devkitarm-rules#8]
I'm trying to compile an existing project that has structure like so:
source/device.c
source/folder1/device.c
source/folder2/device.c

Using the rules in this repo, the project won't build properly because all each of the files above get compiled to build/device.o.

I'm not really expecting the team to redo your make files to accommodate this
But I could use your advice on what you'd do here.

**Comment by oreo639** [comment]
What is the existing project?

**Comment by talanc** [comment]
https://github.com/Keriew/augustus

e.g.:
src\assets\image.c 
src\building\image.c 
src\core\image.c 
src\figure\image.c 
src\graphics\image.c 
src\map\image.c

**Comment by talanc** [comment]
Also image.c is just 1 of 55 duplicates.

**Comment by WinterMute** [comment]
This isn't really an appropriate place to ask for support building a specific project. Please use the appropriate forum at https://devkitpro.org.

The simple answer is that you shouldn't use these rules to attempt to build projects that have their own build systems but we can get into more detail on the forums.
